version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/docker:20.10.7
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Build Docker images using Docker Compose
          command: |
            docker-compose -f docker-compose-build.yml build
      - run:
          name: Tag Docker images
          command: |
            docker tag reverseproxy taingo30/reverseproxy:latest
            docker tag udagram-api-user taingo30/udagram-api-user:latest
            docker tag udagram-api-feed taingo30/udagram-api-feed:latest
            docker tag udagram-frontend taingo30/udagram-frontend:latest
      - run:
          name: Login to DockerHub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push Docker images to DockerHub
          command: |
            docker push taingo30/reverseproxy:latest
            docker push taingo30/udagram-api-user:latest
            docker push taingo30/udagram-api-feed:latest
            docker push taingo30/udagram-frontend:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-and-push
